# Generated by Django 3.1.7 on 2021-03-25 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=100)),
                ('infoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.info')),
            ],
        ),
    ]
