# Generated by Django 3.1.7 on 2021-03-25 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('info', '0001_initial'),
        ('contribution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500)),
                ('time', models.TimeField(auto_now_add=True)),
                ('contributionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contribution.contribution')),
                ('infoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.info')),
            ],
        ),
    ]
