# Generated by Django 3.1.7 on 2021-03-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('facultyID', models.AutoField(primary_key=True, serialize=False)),
                ('facultyName', models.CharField(max_length=100)),
            ],
        ),
    ]
