# Generated by Django 3.1.7 on 2021-03-25 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('contributionID', models.AutoField(primary_key=True, serialize=False)),
                ('subDate', models.DateTimeField(blank=True)),
                ('aprvDate', models.DateTimeField(blank=True)),
                ('status', models.BooleanField(default=False)),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('document', models.FileField(upload_to=None)),
                ('infoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.info')),
            ],
        ),
    ]
